# from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from signup.views import AdvisorRegistration, SearchPincode
admin.autodiscover()

urlpatterns = [
    url(r'^$', views.signup, name='signup'),
    url(r'^register/', views.register),
    url(r'^check_email/', views.check_email, name="check_email"),
    url(r'^reset/', views.send_forgot_password_link, name='forgot_password_reset'),
    # url(r'^business_information/', views.business_information,
    #     name="business_information"),
    url(r'^education/', views.ekyc_step5, name="education"),
    url(r'^upload_file/?$', views.upload_file, name='upload_file'),
    url(r'^recheck/', views.forgot_password_change, name='forgot_password_change'),
    url(r'^user_profile_answer/', views.user_profile_answer, name='user_profile_answer'),
    url(r'^user_createpassword/', views.user_createpassword, name='user_createpassword'),
    url(r'^user_checkpassword/', views.user_checkpassword, name='user_checkpassword'),
    url(r'^search_pincode/', login_required(SearchPincode.as_view()),
        name='search_pincode'),
    url(r'^delete_upload_file/', views.delete_upload_file, name='delete_upload_file'),
    url(r'^personal_information/', login_required(AdvisorRegistration.as_view()),
        name='personal_information'),
    url(r'^show_regulatory_doc_modal/',
        views.show_regulatory_doc_modal, name='show_regulatory_doc_modal'),
    url(r'^user_profile_basicdetails/',
        views.user_profile_basicdetails, name='user_profile_basicdetails'),
    url(r'^onchange_save_field/', views.onchange_save_field, name='onchange_save_field'),
    url(r'^onchange_save_questions/',
        views.onchange_save_questions, name='onchange_save_questions'),
    url(r'^invite_advisor_modal/', views.invite_advisor, name='invite_advisor'),
    url(r'^save_invite_advisor_modal/',
        views.save_invite_advisor, name='save_invite_advisor'),
    url(r'^crisal_id_points/', views.crisal_id_points, name="crisal_id_points"),
    url(r'^rate_advisor/', views.rate_advisor, name='rate_advisor'),
    url(r'^advisor_rating/(?P<activation_key>[a-zA-Z0-9]+)$',
        views.advisor_rating, name='advisor_rating'),
    url(r'^invite_to_rate/', views.invite_to_rate, name='invite_to_rate'),
    url(r'^invite_advisor_to_rate/', views.invite_advisor_to_rate,
        name='invite_advisor_to_rate'),
    url(r'^member_referral/', views.refer_member, name='refer_member'),
    url(r'^business_information/',
        views.personal_information, name='business_information'),
    url(r'^download_advisor_profile/',
        views.download_advisor_profile,        name='download_advisor_profile'),
    url(r'^nationality/$', views.onchange_save_nationality,
        name='onchange_save_nationality'),
    url(r'^onchange_save_rera_fields/',
        views.onchange_save_rera_fields,     name='onchange_save_rera_fields'),
    url(r'^check_and_save_secondary_email/',
        views.check_and_save_secondary_email, name='check_and_save_secondary_email'),
    url(r'^my_belief/', views.save_my_belief, name='onchange_mybelief'),
    url(r'^save_adhaar/', views.save_adhaar, name='save_adhaar'),

    # Profile Preview URL after saving all the steps in Kyc form
    url(r'^preview_pdf_kyc/', views.preview_pdf_kyc, name='preview_pdf_kyc'),
    url(r'^add_sales_acomplishments',
        views.add_sales_acomplishments,       name='add_sales_acomplishments'),
    url(r'^edit_profile/', views.edit_profile, name='edit_profile'),
    url(r'^save_profile/', views.save_profile, name='save_profile'),
    url(r'^setpassword/', views.setpassword, name='setpassword'),
    url(r'^check_valid_domain/', views.check_valid_domain, name='check_valid_domain'),
    url(r'^check_email_for_business_information/',
        views.check_email_for_business_information,
        name='check_email_for_business_information'),
    url(r'^crisil_certificate_pdf/',
        views.crisil_certificate_pdf.as_view(), name='crisil_certificate'),
    url(r'^upload_eipv_documents/',
        views.upload_eipv_documents, name='upload_eipv_documents'),
    url(r'^submit_eipv/', views.submit_eipv, name='submit_eipv'),
    url(r'^user_repput', views.user_repput, name='user_repput'),
    # aadhaar url
    url(r'^verification_process/',
        views.aadhaar_verification, name='verification_process'),
    url(r'^submit_eipv_doc/', views.submit_eipv_doc, name='submit_eipv_doc'),
    url(r'^personal_info_forms/', views.personal_info_forms, name='personal_info_forms'),
    url(r'^send_otp/', views.send_otp, name='send_otp'),
    url(r'^verify_otp/', views.verify_otp, name='verify_otp'),
    url(r'^save_foot_print_verification/',
        views.save_foot_print_verification, name='save_foot_print_verification'),
    url(r'^delete_foot_print_verification/',
        views.delete_foot_print_verification,   name='delete_foot_print_verification'),
    url(r'^check_registration_data/',
        views.check_registration_data_exists, name='check_registration_data_exists'),
    url(r'^show_education_qualification/',
        views.show_education_qualification, name='show_education_qualification'),
    url(r'^submit_verification/', views.submit_verification,
        name='submit_verification'),
    url(r'^update_verification_type/', views.update_verification_type,
        name='update_verification_type'),
    url(r'^face_capture/', views.face_capture, name='face_capture'),
    url(r'^check_user_exist/', views.check_user_exist, name='check_user_exist'),
    url(r'^educational_qualification/', views.educational_qualification,
        name='educational_qualification'),
    url(r'^investor_identity/', views.investor_identity,
        name='investor_identity')
]
