"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'syzg-=ovamkuuyx)y^zppfs$ps0l=53(c@)fz+d7yyg4)fc@27'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Site Settings
SITE_ID = 1

ALLOWED_HOSTS = []

# Application definition
DEFAULT_APPS = (
    # Apps bundled with Django
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'debug_toolbar',
)

THIRD_PARTY_APPS = (
    # Third party apps
    'widget_tweaks',
    'django_mandrill',
    'storages',
    'datetimewidget',
    'simple_history',
    'longerusernameandemail',
    'maintenance_mode',
    'rest_framework',
    'mathfilters',
)

LOCAL_APPS = (
    # REIA Apps
    'signup',
    'login',
    'home',
    'blog',
    'nfadmin',
    'blockchain',
    'stream',
    'datacenter',
    'dashboard',
    'common',
    'logAll',
    'company',
    'advisor_check',
    'nsdl',
    'reputation_index',
    'my_identity',
    'revenue',
    'my_growth',
    'reputation_index_signals',
    'my_repute',
    'member',
    'wpb'
)

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS

# Django Middleware Class
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'login.middleware.LoginRequiredMiddleware',
    'logAll.middleware.LogAllMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'maintenance_mode.middleware.MaintenanceModeMiddleware',
)

ROOT_URLCONF = 'reia.urls'

## Templates Directories ##
BASE_TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')
HOME_TEMPLATE_DIR = os.path.join(BASE_DIR, 'home/templates')
LOGIN_TEMPLATE_DIR = os.path.join(BASE_DIR, 'login/templates')
SIGNUP_TEMPLATE_DIR = os.path.join(BASE_DIR, 'signup/templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_TEMPLATE_DIR,HOME_TEMPLATE_DIR,LOGIN_TEMPLATE_DIR,SIGNUP_TEMPLATE_DIR,],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
                'login.context_processors.general_settings',
                'common.context_processors.crisil_status_flags',
                'common.context_processors.common_objects',
                'common.context_processors.ip_country',
                'common.context_processors.common_constants',
            ],
            'loaders': [
                'app_namespace.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = 'reia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
database_host = "[DB_HOST_NAME]"
database_user = "[DB_USER_NAME]"
database_pass = "[DB_USER_PASS]"
if "DB_HOST_NAME" in database_host:
    database_host = "localhost"
    database_user = "nfadmin"
    database_pass = "nfadmin@123#"

DATABASES = {
    "default": {
        # Ends with "postgresql_psycopg2", "mysql", "sqlite3" or "oracle".
        "ENGINE": "django.contrib.gis.db.backends.mysql",
        # DB name or path to database file if using sqlite3.
        "NAME": "nfdb",
        # Not used with sqlite3.
        "USER": database_user,
        # Not used with sqlite3.
        "PASSWORD": database_pass,
        # Set to empty string for localhost. Not used with sqlite3.
        "HOST": database_host,
        # Set to empty string for default. Not used with sqlite3.
        "PORT": "3306",
    }
}

## USER Profile
AUTH_PROFILE_MODULE = 'datacenter.UserProfile'

# -----------------------------------------------------------------------
# Advisor Check DataBase settings
# -----------------------------------------------------------------------
ADVISOR_CHECK_DB_ALIAS = "advisor_check"
advisor_check_database_engine = "django.contrib.gis.db.backends.mysql"
advisor_check_database_name = "advisor_db"
advisor_check_database_user = "[ADVISOR_DB_USER_NAME]"
advisor_check_database_pass = "[ADVISOR_DB_USER_PASS]"
advisor_check_database_host = "[ADVISOR_DB_HOST_NAME]"
advisor_check_database_port = "3306"

if "ADVISOR_DB_HOST_NAME" in advisor_check_database_host:
    advisor_check_database_engine = "django.contrib.gis.db.backends.mysql"
    advisor_check_database_name = "advisor_db"
    advisor_check_database_user = "advisoradmin"
    advisor_check_database_pass = "advisoradmin@123#"
    advisor_check_database_host = "localhost"
    advisor_check_database_port = "3306"

advisor_check_db_settings = {
    "ENGINE": advisor_check_database_engine,
    "NAME": advisor_check_database_name,
    "USER": advisor_check_database_user,
    "PASSWORD": advisor_check_database_pass,
    "HOST": advisor_check_database_host,
    "PORT": advisor_check_database_port,
}
# appending to django databases
DATABASES.update({ ADVISOR_CHECK_DB_ALIAS:advisor_check_db_settings})
# -----------------------------------------------------------------------
DATABASE_ROUTERS = ['advisor_check.routers.AdvisorCheckRouter']

# DataBase Fixtures
FIXTURE_DIRS = (os.path.join(BASE_DIR, 'fixtures'),)

# cache database configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:redisAdmin@127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        }
    }
}

# Cache time to live is 5 minutes in general.
CACHE_TTL = 60 * 5



# Rest FrameWork
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
}

JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=30000),
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Calcutta'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = "/home/kantanand/projects/NF/reia/static"
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static")
# STATIC_ROOT = os.path.join(BASE_DIR, "static")


MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR,'uploads')
LOADING_STATIC_FOR_PDF = os.path.join(BASE_DIR, "static")

# =====================================================================
# Login - Logout - Login Exempt & Auth URLs
# =====================================================================
LOGIN_URL = '/login/'
LOGOUT_URL = '/logout'
LOGIN_REDIRECT_URL = '/'
LOGIN_EXEMPT_URLS = (
    r'^get_in_touch/',
    r'^contact_us_reia/',
    r'^signup/*',
    r'^api/*', # allow the entire /* subsection
    r'^blog/feed/', # allow the entire RSS /* subsection
    # remove urls after confirmation
    # r'^profile/(?P<slug>[a-zA-Z0-9]+)/$',
    r'^terms_and_condition/',
    r'^privacy_and_policy/',
    r'^disclaimer_reia/',
    r'^dashboard/disown_member_api/(?P<referral_code>[a-zA-Z0-9]+)/$',
    r'^steps_to_recover_password/',
    r'^company/',
    r'^server_health/*',
    r'^reputation-index/*',
    r'^revenue/*',
    r'^guest/(?P<slug>[a-zA-Z0-9]+)/',
    # remove urls after confirmation
    # r'^repute_index/(?P<slug>[a-zA-Z0-9]+)/',
    r'^my_identity/save_guest_details/',
    r'^digital-identity-modal/',
    r'^micro-learning-modal/',
    r'^reputation-index-modal/',
    r'^load-reputation-video-modal/',
    r'^dashboard/follower_advisor_mapping/',
    r'^member/get_member_response/',
    r'^member/get_member_rating',
    r'^member/get_profile_details/',
    r'^summary_of_abotmi_privacy_policy/',
    r'^code_of_coduct/',
    r'^get_advice_page/',
    r'^build_page/',
    r'^opportunities_page/',
    r'^my_repute/my_repute_static/',
    r'^summary_of_terms_condtions/',
    r'^advisor_page/',
    r'^cookie_policy/',
    r'^copyright_policy/',
    r'^ethical_commitment_page/',
    r'^my_repute/manage_reputation/',
    r'^my_repute/build_reputation/',
    r'^my_repute/share_reputation/',
    r'^purpose_page/',
    r'^people_page/',
    r'^partners_page/',
    r'^protection_page/',
    r'^refer_advice_page/',
    r'^rate_advice_page/',
    r'^refer_friend/',
    
)
# =====================================================================

# ====================================================================
# wkhtml PDF configuration need: sudo apt-get install wkhtmltopdf
# ====================================================================
WKHTMLTOPDF_CMD = '/usr/bin/wkhtmltopdf'

# ====================================================================
# MAINTENANCE_MODE Settings
# ====================================================================
#if True the maintenance-mode will be activated
MAINTENANCE_MODE = False
#if True the staff will not see the maintenance-mode page
MAINTENANCE_MODE_IGNORE_STAFF = False
#if True the superuser will not see the maintenance-mode page
MAINTENANCE_MODE_IGNORE_SUPERUSER = False
#list of ip-addresses that will not be affected by the maintenance-mode
#ip-addresses will be used to compile regular expressions objects
MAINTENANCE_MODE_IGNORE_IP_ADDRESSES = ()
#list of urls that will not be affected by the maintenance-mode
#urls will be used to compile regular expressions objects
MAINTENANCE_MODE_IGNORE_URLS = ()
#the absolute url where users will be redirected to during maintenance-mode
MAINTENANCE_MODE_REDIRECT_URL = None
#the template that will be shown by the maintenance-mode page
MAINTENANCE_MODE_TEMPLATE = '503.html'
#the path of the function that will return the template context -> 'myapp.mymodule.myfunction'
MAINTENANCE_MODE_TEMPLATE_CONTEXT = None
# ====================================================================

# ====================================================================
# Log all interaction with user to the DB
# ref: https://djangosnippets.org/snippets/2325/
# ====================================================================
#Should we log full HTML responses?
LOGALL_LOG_HTML_RESPONSE = False
# ====================================================================

# =====================================================================
# Mail Settings
# =====================================================================
EMAIL_BACKEND = 'django_mandrill.mail.backends.mandrillbackend.EmailBackend'
MANDRILL_API_KEY = "T17HP-nB5NEYp8sYrqQ1PQ"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'northfacing.in@gmail.com'
EMAIL_HOST_PASSWORD = 'northfacing@vol'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
REIA_ADMIN_EMAIL  = 'contact@abotmi.com'
# =====================================================================

# ====================================================================
# Third Party API Keys
# ====================================================================
# ClickMeeting Webinar API KEY
WEBINAR_API_KEY = "us131b149b26896d341ee0d9ba5bbca6f03bb59a4e"

# Social Media Counter
SOCIAL_MEDIA_COUNT_URL = "https://free.sharedcount.com/url"
SHARED_COUNT_API_KEY = "8e22999cdb80b4c148986a8a83702f712da2897c"

# SMS Integration Details
# commented for backup
# SMS_URL = 'http://alerts.valueleaf.com/api/v3/?method=sms'

SMS_URL = 'http://sms.valueleaf.com/sms/user/urlsms.php'
SMS_API = 'A22b641e72abf752bce522605284a9bcc'
SMS_SENDER_ID = 'UPWRDZ'
SMS_USERNAME = "mobisirnf"
SMS_PASSWORD = "Go to meeting@10am"
# Textient API AI
RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
RANK_API_URL = "https://rankapi.int.textient.com/v1"

# IP Location : ipinfo.io token
IP_INFO_URL = "https://ipinfo.io"
IP_INFO_TOKEN = "bac2b54bea24c5"
# ====================================================================

# =====================================================================
## GLOBAL CONSTANTS ##
# =====================================================================
PRODUCT_NAME = 'UPWRDZ'

server_name = "[SERVER_NAME]"
server_protocol = "https"
server_port = "443"
if "SERVER_NAME" in server_name:
    server_protocol = "http"
    server_name = "localhost"
    server_port = "8000"

DEFAULT_PROTOCOL = server_protocol
DEFAULT_HOST = server_name
DEFAULT_PORT = server_port
DEFAULT_DOMAIN_NAME = DEFAULT_HOST+':'+DEFAULT_PORT
DEFAULT_DOMAIN_URL = DEFAULT_PROTOCOL+'://'+DEFAULT_HOST
DEFAULT_DOMAIN_URL1 = DEFAULT_PROTOCOL+'://'+DEFAULT_HOST+':'+DEFAULT_PORT
# SERVER_DOWNLOAD_URL = 'https://dev.reiaglobal.com'

# USER_UPLOAD_DOCUMENTS_LINK
USER_UPLOAD_DOCUMENTS_LINK = DEFAULT_DOMAIN_URL+"/signup/submit_documents/"

# next_url link
NEXT_URL_LINK = DEFAULT_DOMAIN_URL+'/'

#Referral URLs
REFERRAL_LINK = DEFAULT_DOMAIN_URL+"/signup/?ref_link="

#Disown URLs
DISOWN_LINK = DEFAULT_DOMAIN_URL+"/dashboard/disown_member_api/"

#Single page URL link
GOOGLE_SINGLE_URL   = DEFAULT_DOMAIN_URL+"/login/google_sm/"
FACEBOOK_SINGLE_URL = DEFAULT_DOMAIN_URL+"/login/facebook_sm/"
LINKEDIN_SINGLE_URL = DEFAULT_DOMAIN_URL+"/login/linkedin_sm/"
# =====================================================================


# =====================================================================
# Check For Domain name and update API keys and Third party Apps URLs
# =====================================================================
stream_host = "http://localhost"
stream_port = "8090"
icore_host  = "https://test.icoreindia.com"
icore_port  = "443"

facebook_api_key = ""
facebook_app_secret = ""
google_api_key = ""
linkedin_api_key = ""

uplyf_server_name = "https://dev.uplyf.com"
uplyf_port = "443"

if server_name == 'upwrdz.com':
    facebook_api_key = "250886972078444"
    facebook_app_secret = "5ae3fbeb6f4ae8abb0b30194895e97ee"
    google_api_key \
    = "694526678521-gi680vetg016n0g2bfpevkmecmo68il1.apps.googleusercontent.com"
    linkedin_api_key = "81w8pcansqqyzh"
    stream_host = "https://stream.ac.in"
    stream_port = "80"
    icore_host  = "https://icoreindia.com"
    icore_port  = "443"
    aws_storage_bucket_name = "upwrdzprod"
    aws_access_key_id = 'AKIAJYQWXOEBIDPIAHOA'
    aws_secret_access_key = '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'
    uplyf_server_name = 'https://uplyf.com'
    uplyf_username = 'reiaspoc@reiaglobal.com'
    uplyf_password = 'reiaspoc@testmobisir'
    ip_info_token = "13300771afb0ed"
    # temprory
    upwrdz_api_username = ""
    upwrdz_api_password = ""
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://rankapi.int.textient.com/v1"
    MEETUP_GROUP_NAME = "meetup-group-sshjAoTJ"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://bc.upwrdz.com"
    BLOCKCHAIN_IP = "bc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x2e47e1dcf60a8619cf64bfd77325ff114f08e0b9"
    BLOCKCHAIN_ADMIN_PWD = "NF@1.6fib"
    mlegion_server_name = 'https://mlegion.net'
    mlegion_username='upwrdzspoc@upwrdz.com'
    mlegion_password='upwrdzspoc@mobisir'

elif server_name == 'prod.upwrdz.com':
    facebook_api_key = "1897563187185148"
    facebook_app_secret = "7a0860c655c9f226a0d3e1719dd5b241"
    google_api_key \
    = "694526678521-j1p26g9jsq1df0h24ieh64dq66to18sp.apps.googleusercontent.com"
    linkedin_api_key = "81aje8ktskwhhk"
    stream_host = "https://stream.ac.in"
    stream_port = "80"
    icore_host  = "https://test.icoreindia.com"
    icore_port  = "443"
    # aws_storage_bucket_name = "upwrdzprod"
    aws_storage_bucket_name = "upwrdzdev"
    aws_access_key_id = 'AKIAIHFRD2K6K3KW4CPQ'
    aws_secret_access_key = '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'
    uplyf_server_name = 'https://test.uplyf.com'
    uplyf_username = 'reiatestspoc@reiaglobal.com'
    uplyf_password = 'reiaspoc@testmobisir'
    ip_info_token = "13300771afb0ed"
    # temprory
    upwrdz_api_username = ""
    upwrdz_api_password = ""
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://rankapi.int.textient.com/v1"
    MEETUP_GROUP_NAME = "meetup-group-sshjAoTJ"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://devbc.upwrdz.com"
    BLOCKCHAIN_IP = "devbc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x0f707b8f00c4e5f83c5a868800cddad3b1a02e8d"
    BLOCKCHAIN_ADMIN_PWD = "restart"
    mlegion_server_name = 'https://dev.mlegion.net'
    mlegion_username = 'upwrdzdevspoc@upwrdz.com'
    mlegion_password = 'upwrdzspoc@devmobisir'

elif server_name == 'demo.upwrdz.com':
    facebook_api_key = "112974982695628"
    facebook_app_secret = "829f882ed41daa3cda9d8b0b4a82c801"
    google_api_key \
    = "694526678521-bv3p1basvvhn7n53p6g83lm20eui7ah6.apps.googleusercontent.com"
    linkedin_api_key = "81ce0p6uw4006g"
    stream_host = "https://test.stream.ac.in/"
    stream_port = "80"
    icore_host  = "https://test.icoreindia.com"
    icore_port  = "443"
    # AWS Bucket and SSEKMS_id
    aws_storage_bucket_name = 'upwrdztest'
    aws_ssekms_key_id = 'de937575-6c8b-4881-ae1d-6ef19407d37c'
    # OLD keys
    aws_access_key_id = 'AKIAIHFRD2K6K3KW4CPQ'
    aws_secret_access_key = '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'
    # Uplyf Server Details
    uplyf_server_name = 'https://demo.uplyf.com'
    uplyf_username = 'reiatestspoc@reiaglobal.com'
    uplyf_password = 'reiaspoc@testmobisir'
    ip_info_token = "13300771afb0ed"
    # temprory
    upwrdz_api_username = ""
    upwrdz_api_password = ""
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://rankapi-dev.int.textient.com/v1"
    MEETUP_GROUP_NAME = "upwrdz-meetup-group"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://devbc.upwrdz.com"
    BLOCKCHAIN_IP = "devbc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x0e5b3ef7ca7e770bb5762fe2e3c83bb207489d3f"
    BLOCKCHAIN_ADMIN_PWD = "restart"
    mlegion_server_name = 'https://dev.mlegion.net'
    mlegion_username = 'upwrdzdevspoc@upwrdz.com'
    mlegion_password = 'upwrdzspoc@devmobisir'

elif server_name == 'test.upwrdz.com':
    facebook_api_key = "1959007544334808"
    facebook_app_secret = "40a3ef0795fdc8e1611188956d257678"
    google_api_key \
    = "694526678521-lmmqf45n58jb29js9k8m92veaqqilrnm.apps.googleusercontent.com"
    linkedin_api_key = "81548p0fvaq3g7"
    stream_host = "https://test.stream.ac.in/"
    stream_port = "80"
    icore_host  = "https://test.icoreindia.com"
    icore_port  = "443"
    aws_storage_bucket_name = "upwrdztest-dac"
    aws_access_key_id = 'AKIAIHFRD2K6K3KW4CPQ'
    aws_secret_access_key = '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'
    uplyf_server_name = 'https://test.uplyf.com'
    uplyf_username = 'reiatestspoc@reiaglobal.com'
    uplyf_password = 'reiaspoc@testmobisir'
    ip_info_token = "bac2b54bea24c5"
    # temprory
    upwrdz_api_username = 'admin@mobisir.net'
    upwrdz_api_password = 'nftp@123#'
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://rankapi-test.int.textient.com/v1"
    MEETUP_GROUP_NAME = "upwrdz-meetup-group"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://devbc.upwrdz.com"
    BLOCKCHAIN_IP = "devbc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x0e5b3ef7ca7e770bb5762fe2e3c83bb207489d3f"
    BLOCKCHAIN_ADMIN_PWD = "restart"
    mlegion_server_name = 'https://dev.mlegion.net'
    mlegion_username = 'upwrdzdevspoc@upwrdz.com'
    mlegion_password = 'upwrdzspoc@devmobisir'

elif server_name == 'dev.upwrdz.com':
    facebook_api_key = "1969649263269659"
    facebook_app_secret = "512226ba24722c9944db30a39dc5e77c"
    google_api_key \
    = "694526678521-ajjgeln3hbq7aefat5hu5iteega6d03s.apps.googleusercontent.com"
    linkedin_api_key = "81o2rhqmuyhm9t"
    stream_host = "https://test.stream.ac.in/"
    stream_port = "80"
    icore_host  = "https://test.icoreindia.com"
    icore_port  = "443"
    aws_storage_bucket_name = "upwrdzdev-dac"
    aws_access_key_id = 'AKIAIHFRD2K6K3KW4CPQ'
    aws_secret_access_key = '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'
    uplyf_server_name = 'https://dev.uplyf.com'
    uplyf_username = 'reiadevspoc@reiaglobal.com'
    uplyf_password = 'reiaspoc@devmobisir'
    ip_info_token = "bac2b54bea24c5"
    # temprory
    upwrdz_api_username = 'admin@mobisir.net'
    upwrdz_api_password = 'nftp@123#'
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://rankapi-dev.int.textient.com/v1"
    MEETUP_GROUP_NAME = "upwrdz-meetup-group"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://devbc.upwrdz.com"
    BLOCKCHAIN_IP = "devbc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x0e5b3ef7ca7e770bb5762fe2e3c83bb207489d3f"
    BLOCKCHAIN_ADMIN_PWD = "restart"
    mlegion_server_name = 'https://dev.mlegion.net'
    mlegion_username = 'upwrdzdevspoc@upwrdz.com'
    mlegion_password = 'upwrdzspoc@devmobisir'

elif server_name == 'dev1.upwrdz.com':
    facebook_api_key = "1969649263269659"
    facebook_app_secret = "512226ba24722c9944db30a39dc5e77c"
    google_api_key \
    = "694526678521-mef1q2ctm0aicevuu8e285rog7kmijrd.apps.googleusercontent.com"
    linkedin_api_key = "81o2rhqmuyhm9t"
    stream_host = "https://test.stream.ac.in/"
    stream_port = "80"
    icore_host  = "https://test.icoreindia.com"
    icore_port  = "443"
    aws_storage_bucket_name = "upwrdzdev"
    aws_access_key_id = 'AKIAIHFRD2K6K3KW4CPQ'
    aws_secret_access_key = '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'
    uplyf_server_name = 'https://dev.uplyf.com'
    uplyf_username = 'reiadevspoc@reiaglobal.com'
    uplyf_password = 'reiaspoc@devmobisir'
    ip_info_token = "bac2b54bea24c5"
    # temprory
    upwrdz_api_username = ""
    upwrdz_api_password = ""
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://rankapi-dev.int.textient.com/v1"
    MEETUP_GROUP_NAME = "upwrdz-meetup-group"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://devbc.upwrdz.com"
    BLOCKCHAIN_IP = "devbc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x0e5b3ef7ca7e770bb5762fe2e3c83bb207489d3f"
    BLOCKCHAIN_ADMIN_PWD = "restart"
    mlegion_server_name = 'https://dev.mlegion.net'
    mlegion_username = 'upwrdzdevspoc@upwrdz.com'
    mlegion_password = 'upwrdzspoc@devmobisir'

elif server_name == 'dev2.upwrdz.com':
    facebook_api_key = "518547841846214"
    facebook_app_secret = "bc9263914d6b72945b8ec674a7fb31fc"
    google_api_key \
    = "694526678521-mef1q2ctm0aicevuu8e285rog7kmijrd.apps.googleusercontent.com"
    linkedin_api_key = "81o2rhqmuyhm9t"
    stream_host = "https://test.stream.ac.in/"
    stream_port = "80"
    icore_host  = "https://test.icoreindia.com"
    icore_port  = "443"
    aws_storage_bucket_name = "upwrdzdev-dac"
    aws_ssekms_key_id = '08747d92-ac46-45b4-a67e-ae622225359d'
    aws_access_key_id = 'AKIAIHFRD2K6K3KW4CPQ'
    aws_secret_access_key = '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'
    uplyf_server_name = 'https://dev.uplyf.com'
    uplyf_username = 'reiadevspoc@reiaglobal.com'
    uplyf_password = 'reiaspoc@devmobisir'
    ip_info_token = "bac2b54bea24c5"
    # temprory
    upwrdz_api_username = ""
    upwrdz_api_password = ""
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://35.154.213.92/v1"
    MEETUP_GROUP_NAME = "upwrdz-meetup-group"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://devbc.upwrdz.com"
    BLOCKCHAIN_IP = "devbc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x0e5b3ef7ca7e770bb5762fe2e3c83bb207489d3f"
    BLOCKCHAIN_ADMIN_PWD = "restart"
    mlegion_server_name = 'https://dev.mlegion.net'
    mlegion_username = 'upwrdzdevspoc@upwrdz.com'
    mlegion_password = 'upwrdzspoc@devmobisir'

else:
    facebook_api_key = "278212815921681"
    facebook_app_secret = "5a6b654ccccf0ef726b9fbcf0ab4d863"
    google_api_key \
    = "266742724883-g2al1rhd2c8ejulvhn6pn439o2h3goos.apps.googleusercontent.com"
    linkedin_api_key = "75xgpkd7ynz4hy"
    stream_host = "https://test.stream.ac.in/"
    stream_port = "80"
    icore_host  = "https://test.icoreindia.com"
    icore_port  = "443"
    uplyf_server_name = 'http://localhost:8010'
    uplyf_port = "443"
    uplyf_username = 'admin@mobisir.net'
    uplyf_password = 'nftp@123#'
    ip_info_token = "bac2b54bea24c5"
    # temprory
    upwrdz_api_username = 'admin@mobisir.net'
    upwrdz_api_password = 'nftp@123#'
    RANK_API_KEY = "y82QiA9dfH2DsnLr7q8sX5xzQikeMDdT97I4auv2"
    RANK_API_URL = "https://192.168.0.202/v1"
    MEETUP_GROUP_NAME = "upwrdz-meetup-group"
    MEETUP_KEY = "33e411b637f44447b4a795c335c471a"
    BLOCKCHAIN_URL = "https://devbc.upwrdz.com"
    BLOCKCHAIN_IP = "devbc.upwrdz.com"
    BLOCKCHAIN_PORT = 443
    BLOCKCHAIN_ADMIN_ACCOUNT = "0x0e5b3ef7ca7e770bb5762fe2e3c83bb207489d3f"
    BLOCKCHAIN_ADMIN_PWD = "restart"
    mlegion_server_name = 'http://localhost:5000'
    mlegion_username = 'admin@mobisir.net'
    mlegion_password = 'nftp@123#'

# =====================================================================

# =====================================================================
#  Social Media Auth Keys and Redirect URLs
# =====================================================================
# Social Media Api Keys
FACEBOOK_API = facebook_api_key
FACEBOOK_APP_SECRET = facebook_app_secret
GOOGLE_CLIENTID = google_api_key
LINKEDIN_API = linkedin_api_key

# Social Media Redirect URLs
GOOGLE_REDIRECT = DEFAULT_DOMAIN_URL
LINKEDIN_SUBMITTED_URL = DEFAULT_DOMAIN_URL
LINKEDIN_IMAGE_URL = DEFAULT_DOMAIN_URL+"/static/images/sm-banner.jpg"
# =====================================================================

# Aadhaar request urls
AADHAAR_INITIATION_URL =  'https://prod.aadhaarbridge.com/kua/_init'
AADHAAR_FETCH_KYC_URL = 'https://prod.aadhaarbridge.com/kua/_kyc'

# IPINFO TOKEN
IP_INFO_TOKEN = ip_info_token

# =====================================================================
# NORTHFACING Appliactions
# =====================================================================

# STREAM SPOC DETAILS
STREAM_HOST     = 'http://localhost:8020'
STREAM_PORT     = '8020'
STREAM_URL      = STREAM_HOST
STREAM_AUTH_URL = STREAM_URL+'/api/get_auth_token'
STREAM_USER_ID  = "reiaglobal@gmail.com"
STREAM_PASSWORD = "abc123"
STREAM_TOKEN    = None

# ICORE DETAILS
ICORE_HOST      = icore_host
ICORE_PORT      = icore_port
ICORE_API_URL   = ICORE_HOST+":"+ICORE_PORT+"/wp-json"
ICORE_WP_URL    = ICORE_HOST+":"+ICORE_PORT+"/wp-admin"
ICORE_ADMIN     = "nfadmin"
ICORE_ADMIN_PWD = "NF@1.6fib"
# temprory fixing once we got ssl certification we can use commented code
#ICORE_XMLRPC    = ICORE_HOST+":"+ICORE_PORT+"/xmlrpc.php"
ICORE_XMLRPC = "https://test.icoreindia.com:443/xmlrpc.php"

# UPLYF Server name
UPLYF_TITLE ='UPLYF'
UPLYF_SERVER = uplyf_server_name
UPLYF_USER_NAME = uplyf_username
UPLYF_PASSWORD = uplyf_password
UPWRDZ_USERNAME = upwrdz_api_username
UPWRDZ_PASSWORD = upwrdz_api_password
# UPLYF_USER_NAME = 'admin@mobisir.net'
# UPLYF_PASSWORD = 'nftp@123#'
UPLYF_PORT     = uplyf_port
UPLYF_URL      = UPLYF_SERVER+":"+UPLYF_PORT
UPLYF_AUTH_URL = UPLYF_URL+'/api/get_auth_token'
UPLYF_TOKEN    = None

# MLEGION Server name
MLEGION_SERVER = mlegion_server_name
MLEGION_USERNAME = mlegion_username
MLEGION_PASSWORD = mlegion_password

# =====================================================================
# ====================================================================
# LOGGING Settings
# ====================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'reia.log',
            'formatter': 'verbose'
        },
        'console':{
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'django.request': {
           'handlers': ['file'],
           'propagate': False,
           'level': 'DEBUG'
        },
        'login': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'signup': {
            'handlers': ['file'],
            'level': 'DEBUG',
        },
        'home': {
            'handlers':['file'],
            'level' : 'DEBUG',
        },
        'nfadmin':{
            'handlers':['console'],
            'level': 'DEBUG',
        },
        'api': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'uploader':{

            'handlers': ['file'],
            'level': 'DEBUG',

        }
    }
}
# ====================================================================
