# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ABOTMI' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ABOTMI

  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'SVProgressHUD'

end
