# Revenue platform
PLATFORM = "UPWRDZ"
ADVISOR_GROUP = "ADVISOR_GROUP"
CLIENT_GROUP = "CLIENT_GROUP"
ADVISOR_FIRST_TRANSACTION=1
ADVISOR_SECOND_TRANSACTION=2
ADVISOR_THIRD_TRANSACTION=3
# Revenue Type
GET_CERTIFIED_REVENUE_FEE = "GET_CERTIFIED_REVENUE_FEE"
CERTIFIED_PROVIDER_FEE = "CERTIFIED_PROVIDER_FEE"
GET_QUALIFIED_REVENUE_FEE = "GET_QUALIFIED_REVENUE_FEE"
QUALIFIED_PROVIDER_FEE = "QUALIFIED_PROVIDER_FEE"
GET_CONNECTED_REVENUE_FEE = "GET_CONNECTED_REVENUE_FEE"
LISTING_REVENUE_FEE = "LISTING_REVENUE_FEE"
FACILITATION_REVENUE_FEE = "FACILITATION_REVENUE_FEE"
PRODUCT_EDUCATION_REVENUE_FEE = "PRODUCT_EDUCATION_REVENUE_FEE"
PRODUCT_EDUCATION_PROVIDER_FEE = "PRODUCT_EDUCATION_PROVIDER_FEE"
TRANSACTION_MANAGEMENT_FEE = "TRANSACTION_MANAGEMENT_FEE "
FACILITATOR_FEE = "FACILITATOR_FEE"
TRX_LEAD_FEE = "TRX_LEAD_FEE"
TRX_MANAGER_FEE = "TRX_MANAGER_FEE"
FIRST_TRX_BONUS_FEE = "FIRST_TRX_BONUS_FEE"
CLIENT_ADVISOR_FEE = "CLI_ADV_FEE"
CLIENT_ADVISOR_REFER_ADVISOR_FEE_A = "CLI_ADV_REF_ADV_FEE_A"
CLIENT_ADVISOR_REFER_ADVISOR_FEE_B = "CLI_ADV_REF_ADV_FEE_B"
CLIENT_REFER_CLIENT_FEE = "CLI_REF_CLI_FEE"
CLIENT_REFER_CLIENT_FEE_NO_ADVISOR_FEE = "CLI_REF_CLI_FEE_NO_ADV_FEE"