from django.conf.urls import include, url
from . import uplyf_api_views
urlpatterns = [
    url(r'^get-auth-token/', 'rest_framework_jwt.views.obtain_jwt_token'),
    url(r'^api-token-verify/', 'rest_framework_jwt.views.verify_jwt_token'),
    url(r'^api-token-refresh','rest_framework_jwt.views.refresh_jwt_token'),
    url(r'^get-user-list/', 'api.views.get_user_list'),
    url(r'^get-user-details/', 'api.views.get_user_details'),
    url(r'^get-user-profile/', 'api.views.get_user_profile'),
    url(r'^test-list/', 'api.views.test_list'),
    url(r'^get-profile-details/', 'api.views.get_profile_details'),
    url(r'^send-mail-admin-subject/','api.views.send_mail_admin_subject'),
    url(r'^get-dashboard-details/','api.view.get_dashboard_details'),
    url(r'^get-raterank-details/','api.views.get_raterank_details'),
    url(r'^get-peerlist-torate','api.views.get_peerlist_torate'),
    url(r'^get-advisorloop-details','api.views.get_advisorloop_details'),
    url(r'^save-refer-advisor','api.views.save_refer_advisor'),
    url(r'^get-client-details','api.views.get_client_details'),
    url(r'^invite-peerto-rate','api.views.invite_peerto_rate'),
    url(r'^save-advisor-rank','api.views.rate_advisor'),
    url(r'^save-sale-accomplishment','api.views.save_sale_accomplishment'),
    url(r'^get-peerlist-torate','api.views.get_peerlist_torate'),
    url(r'^check-crisil-promocode','api.views.check_crisil_promocode'),
    url(r'^crisil-application','api.views.appling_crisil'),
    url(r'^upload-crisilref-document','api.views.crisil_submit_form'),
    url(r'^disown-member','api.views.disown_member'),
    url(r'^forgot-password','api.views.forgot_password_reset'),
    url(r'^get-in-touch','api.views.contact_us_reia'),
    url(r'^get-icore-specificposts','api.views.get_icore_specificposts'),
    url(r'^rate-icore-post','api.views.rate_icore_post'),
    url(r'^get-icore-categories','api.views.get_icore_categories'),
    url(r'^check-reg-user','api.views.is_register_user'),
     url(r'^aadhar_verification','api.views.aadhar_verification_data'),
    url(r'^is-registerd-user','api.views.is_registerd_user'),
    url(r'^check-email-exists','api.views.check_email_exists_send'),
    url(r'^advisor-events','api.views.get_advisor_events'),
    url(r'^create-direct-signup-user', 'api.views.create_direct_signup_user'),
    url(r'^submit-crisil-renewal','api.views.crisil_renew_submit'),
    url(r'^social-signup','api.views.social_signup_login_details'),
    url(r'^create-aadhaar-form-data','api.views.create_aadhaar_form_data'),
    url(r'^success','api.views.success'),
    url(r'^failure','api.views.failure'),
    url(r'^member-success','api.views.member_sucess'),
    url(r'^member-failed','api.views.member_failed'),
    url(r'^sms-status','api.views.get_smsalert_status'),
    url(r'^change-sms-status','api.views.change_sms_status'),
    url(r'^change-password','api.views.user_createpassword'),
    url(r'^webinar','api.views.create_webinar_mobile'),
    url(r'^uplyfdetails','api.views.uplyfdetails_mobile'),
    url(r'^meetupupdate','api.views.meetupupdate'),  
    url(r'^meetup','api.views.create_meetup_mobile'),
    url(r'^mygrowth_mobile','api.views.create_mygrowth_mobile'),
    url(r'^my_webinar_room_name','api.views.my_webinar_room_name'),
    url(r'^mee_mobile','api.views.list_meetup_mobile'),
    url(r'^web_mobile','api.views.list_webinar_mobile'),
    url(r'^list_member_invitation', 'api.views.list_member_invitation_mobile'),
    url(r'^register_member_webinar', 'api.views.register_member_webinar_mobile'),
    url(r'^delete_meetup','api.views.delete_meetup_event_mobile'),
    url(r'^delete_webinar','api.views.delete_webinar_event_mobile'),
    url(r'^list_mail','api.views.list_mail_invitation_mobile'),
    url(r'^icore-add-media','api.views.icore_add_media'),
    url(r'^icore-add-post','api.views.icore_add_post'),
    url(r'^icore-add-comment','api.views.icore_add_comment'),
    url(r'^upload-file','api.views.upload_file'),
    url(r'^update-profile-details','api.views.save_profile'),
    url(r'^download-profile','api.views.download_advisor_profile'),
    url(r'^add-client-email','api.views.save_new_member'),
    url(r'^check_aadhaar_present','api.views.check_aadhaar_present'),
    url(r'^member_success','api.views.member_success'),
    url(r'^member_failure','api.views.member_failure'),
    url(r'^manage_client_transactions','api.views.manage_client_transactions'),
    url(r'^register_user','api.views.register_user'),
    url(r'^user-profile-answer','api.views.user_profile_answer'),
    url(r'^get-digital-link','api.views.get_digital_link'),
    url(r'^save-digital-link','api.views.save_digital_link'),
    url(r'^delete-digital-link','api.views.delete_foot_print'),
    url(r'^advisor-profile-answer','api.views.advisor_profile_answer'),
    url(r'^user-profile-basicdetails-details','api.views.user_profile_basicdetails_details'),
    url(r'^country-details','api.views.country_details'),
    url(r'^m-submit-eipv','api.views.m_submit_eipv'),
    url(r'^m-upload-eipv-documents','api.views.m_upload_eipv_documents'),
    url(r'^m_delete_uploaded_documents','api.views.delete_uploaded_documents'),
    url(r'^m-eipv-form','api.views.m_eipv_form'),
    url(r'^m-send-otp','api.views.m_send_otp'),
    url(r'^m-verify-otp','api.views.m_verify_otp'),
    url(r'^get-myidentity','api.views.get_myidentity_details'),
    url(r'^get-myhub-details','api.views.get_myhub_details'),
    url(r'^check_refer_advisor_email','api.views.check_refer_advisor_email'),
    url(r'^list_enquiried_clients','api.views.list_enquiried_clients'),
    url(r'^list_client_enquiry','api.views.list_client_enquiry'),
    url(r'^m-geteipv-data','api.views.m_geteipv_data'),
    url(r'^advisor_video_upload_api','api.views.advisor_video_upload_api'),
    url(r'^advisor_video_publish_api','api.views.advisor_video_publish_api'),
	url(r'^send_meetup_invitation_mail','api.views.send_meetup_invitation_mail'),
    url(r'^save_language','api.views.save_language_details'),
    url(r'^save_mypromise','api.views.save_mypromise'),
    url(r'^save_mybelief','api.views.save_mybelief'),
    url(r'^save_contectdetails','api.views.save_contectdetails'),
    url(r'^save_skills','api.views.save_skillsdetails'),
    url(r'^save_advisory_specialization','api.views.save_advisory_specialization'),
    url(r'^save_additional_qualification','api.views.save_additional_qualification'),
    url(r'^regulatory_certification_registration','api.views.regulatory_certification_registration'),
    url(r'^save_clients','api.views.save_clients'),
    url(r'^save_advisor','api.views.save_advisor'),
    url(r'^save_aboutme','api.views.save_aboutme'),
    url(r'^check_adhaar','api.views.is_adharregister_user'),
    url(r'^save_adhaar','api.views.save_adhaar'),
    url(r'^education_detail','api.views.education_details'),
    url(r'^direct_signup','api.views.direct_signup'),
    url(r'^check-email/','api.views.checkEmail'),
    url(r'^save_country_details','api.views.save_country'), 
    url(r'^signup-send-otp','api.views.signup_send_otp'),
    url(r'^signup-resend-otp','api.views.resend_email_mobile_otps_mob'),
    url(r'^validate-otp','api.views.validate_otp_mob'),
    url(r'^save_education_details','api.views.save_educationDetails'),
    url(r'^logout-user','api.views.logout_user'),
    url(r'^save_certification_details','api.views.save_certificationDetails'),
    url(r'^get_server_ip', 'api.views.get_server_ip', name='get_server_ip'),
    # geo reverse coding
    url(r'^get-geo-location/', 'api.views.get_geo_location', name='get_geo_location'),
    # UPLYF API VIEWS
    url(r'^advisor-selection/', uplyf_api_views.advisor_selection),
    url(r'^get_companies_list/', uplyf_api_views.get_companies_list, name="get_companies_list"),
    url(r'^upwrdz_add_client_email/',uplyf_api_views.save_new_member_upwrdz, name="save_new_member_upwrdz"),
    url(r'^get-companies-advisors-list/', uplyf_api_views.get_companies_advisors_list, name='get_companies_advisors_list'),
    url(r'^get-all-register-advisors/', uplyf_api_views.get_all_register_advisors),
    url(r'^get_webniar_list/', uplyf_api_views.get_webniar_list, name="get_webniar_list"),
    url(r'^get_meetup_list/', uplyf_api_views.get_meetup_list, name="get_meetup_list"),
    url(r'^get-advisor-profile-link/', uplyf_api_views.get_advisor_profile_link, name='get_advisor_profile_link'),
    url(r'^get_profile_card', 'api.views.get_profile_card'),
    url(r'^save-client-notification-upwrdz/',
        uplyf_api_views.save_client_notification_upwrdz, 
        name='save-client-notification-upwrdz'
    ),
    url(r'^increament_registered_user_count_by_event_id/',
        uplyf_api_views.increament_registered_user_count_by_event_id,
        name='increament_registered_user_count_by_event_id'
    ),
    
    # FASIA API URLS
    url(r'^check_and_register/', 'api.views.check_and_register', name='check_and_register'),
    url(r'^check_auth_and_redirect/',
        'api.views.check_auth_and_redirect', name='check_auth_and_redirect'),
    url(r'^save_calendly_link','api.views.calendly_save_link')    
     
]
