QUALIFICATION_LIST = (
	('','select'),
	('GRADUATION',
		(
			('Bachelor Hotel Management and Catering Technology(B.H.M.C.T)','Bachelor Hotel Management and Catering Technology(B.H.M.C.T)'),
			('Bachelor Library Science(B.L.Sc)','Bachelor Library Science(B.L.Sc)'),
			('Bachelor of Applied Sciences(B.A.S)','Bachelor of Applied Sciences(B.A.S)'),
			('Bachelor of Architecture(B.Arch)','Bachelor of Architecture(B.Arch)'),
			('Bachelor of Arts Bachelor of Education(B.A. B.Ed)','Bachelor of Arts Bachelor of Education(B.A. B.Ed)'),
			('Bachelor of Arts Bachelor of Law(B.A.LLB)','Bachelor of Arts Bachelor of Law(B.A.LLB)'),
			('Bachelor of Arts(B.A)','Bachelor of Arts(B.A)'),
			('Bachelor of Audiology and Speech Language Pathology(B.A.S.L.P)','Bachelor of Audiology and Speech Language Pathology(B.A.S.L.P)'),
			('Bachelor of Ayurvedic Medicine and Surgery(B.A.M.S)','Bachelor of Ayurvedic Medicine and Surgery(B.A.M.S)'),
			('Bachelor of Business Administration Bachelor of Law(B.B.A LL.B)','Bachelor of Business Administration Bachelor of Law(B.B.A LL.B)'),
			('Bachelor of Business Administration(B.B.A)','Bachelor of Business Administration(B.B.A)'),
			('Bachelor of Business Management(B.B.M)','Bachelor of Business Management(B.B.M)'),
			('Bachelor of Business Studies(B.B.S)','Bachelor of Business Studies(B.B.S)'),
			('Bachelor of Commerce(B.Com)','Bachelor of Commerce(B.Com)'),
			('Bachelor of Communication Journalism(B.C.J)','Bachelor of Communication Journalism(B.C.J)'),
			('Bachelor of Computer Applications(B.C.A)','Bachelor of Computer Applications(B.C.A)'),
			('Bachelor of Computer Science(B.C.S)','Bachelor of Computer Science(B.C.S)'),
			('Bachelor of Dental Surgery(B.D.S)','Bachelor of Dental Surgery(B.D.S)'),
			('Bachelor of Design(B.Des)','Bachelor of Design(B.Des)'),
			('Bachelor of education in Artificial Intelligence(B.Ed AI)','Bachelor of education in Artificial Intelligence(B.Ed AI)'),
			('Bachelor of Education(B.Ed)','Bachelor of Education(B.Ed)'),
			('Bachelor of Electronic Science(B.E.S)','Bachelor of Electronic Science(B.E.S)'),
			('Bachelor of Elementary Education(B.EL.Ed)','Bachelor of Elementary Education(B.EL.Ed)'),
			('Bachelor of Engineering(B.E)','Bachelor of Engineering(B.E)'),
			('Bachelor of Fashion Technology(B.F.Tech)','Bachelor of Fashion Technology(B.F.Tech)'),
			('Bachelor of Financial Investment and Analysis(B.F.I.A)','Bachelor of Financial Investment and Analysis(B.F.I.A)'),
			('Bachelor of Fine Arts(B.F.A)','Bachelor of Fine Arts(B.F.A)'),
			('Bachelor of Fishery Sciences(B.F.S)','Bachelor of Fishery Sciences(B.F.S)'),
			('Bachelor of General Law(B.G.L)','Bachelor of General Law(B.G.L)'),
			('Bachelor of Homeopathic Medicine & Surgery(B.H.M.S)','Bachelor of Homeopathic Medicine & Surgery(B.H.M.S)'),
			('Bachelor of Hospitality and Tourism Management(B.H.T.M)','Bachelor of Hospitality and Tourism Management(B.H.T.M)'),
			('Bachelor of Hotel Management(B.H.M)','Bachelor of Hotel Management(B.H.M)'),
			('Bachelor of Information Systems Management(B.I.S.M)','Bachelor of Information Systems Management(B.I.S.M)'),
			('Bachelor of Labour Management(B.L.M)','Bachelor of Labour Management(B.L.M)'),
			('Bachelor of Law(LL.B)','Bachelor of Law(LL.B)'),
			('Bachelor of Laws(B.L)','Bachelor of Laws(B.L)'),
			('Bachelor of Library and Information Science(B.L.I.S)','Bachelor of Library and Information Science(B.L.I.S)'),
			('Bachelor of Literature(B.Lit)','Bachelor of Literature(B.Lit)'),
			('Bachelor of Medical Laboratory Technology(B.M.L.T)','Bachelor of Medical Laboratory Technology(B.M.L.T)'),
			('Bachelor of Medical Record Science(B.M.R.Sc)','Bachelor of Medical Record Science(B.M.R.Sc)'),
			('Bachelor of Medical Technology(B.M.T)','Bachelor of Medical Technology(B.M.T)'),
			('Bachelor of Medicine Bachelor of Surgery(M.B.B.S)','Bachelor of Medicine Bachelor of Surgery(M.B.B.S)'),
			('Bachelor of Mental Retardation(B.M.R)','Bachelor of Mental Retardation(B.M.R)'),
			('Bachelor of Naturopathy and Yogic Sciences(B.N.Y.Sc)','Bachelor of Naturopathy and Yogic Sciences(B.N.Y.Sc)'),
			('Bachelor of Occupational Therapy(B.O.T)','Bachelor of Occupational Therapy(B.O.T)'),
			('Bachelor of Optometry and Vision Science(B.Optom)','Bachelor of Optometry and Vision Science(B.Optom)'),
			('Bachelor of Pharmacy(B.Pharma)','Bachelor of Pharmacy(B.Pharma)'),
			('Bachelor of Physical Education(B.P.E)','Bachelor of Physical Education(B.P.E)'),
			('Bachelor of Physiotherapy(B.P.T)','Bachelor of Physiotherapy(B.P.T)'),
			('Bachelor of Public Relations(B.P.R)','Bachelor of Public Relations(B.P.R)'),
			('Bachelor of Science Bachelor of Education(B.Sc.B.Ed)','Bachelor of Science Bachelor of Education(B.Sc.B.Ed)'),
			('Bachelor of Science Education(B.S.E)','Bachelor of Science Education(B.S.E)'),
			('Bachelor of Science in Education(B.Sc.Ed)','Bachelor of Science in Education(B.Sc.Ed)'),
			('Bachelor of Science(B.S)','Bachelor of Science(B.S)'),
			('Bachelor of Siddha Medical Sciences(B.S.M.S)','Bachelor of Siddha Medical Sciences(B.S.M.S)'),
			('Bachelor Of Social Work(B.S.W)','Bachelor Of Social Work(B.S.W)'),
			('Bachelor of Socio Legal Sciences Bachelor of Laws(B.S.L.LL.B)','Bachelor of Socio Legal Sciences Bachelor of Laws(B.S.L.LL.B)'),
			('Bachelor of Speech Language & Audiology(B.S.L.A)','Bachelor of Speech Language & Audiology(B.S.L.A)'),
			('Bachelor of Tourism Administration(B.T.A)','Bachelor of Tourism Administration(B.T.A)'),
			('Bachelor of Unani Medicine & Surgery(B.U.M.S)','Bachelor of Unani Medicine & Surgery(B.U.M.S)'),
			('Bachelor of Unani Medicine & Surgery(Kamil e Tob o Jarahat)','Bachelor of Unani Medicine & Surgery(Kamil e Tob o Jarahat)'),
			('Bachelor of Veterinary Science(B.V.Sc)','Bachelor of Veterinary Science(B.V.Sc)'),
			('Bachelors of Technology(B.Tech)','Bachelors of Technology(B.Tech)'),
			('Basic Training Certificate(B.T.C)','Basic Training Certificate(B.T.C)'),
			('Behavioral Healthcare Education(B.H.Ed)','Behavioral Healthcare Education(B.H.Ed)'),
			('Under Graduate Basic Training(U.G.B.T)','Under Graduate Basic Training(U.G.B.T)'),
			('Under Graduate Teacher Training(U.G.T.T)','Under Graduate Teacher Training(U.G.T.T)'),
			('Under Graduate Training(U.G.T)','Under Graduate Training(U.G.T)'),
			('Others','Others'),
		)
	),
	('POST GRADUATION',
		(
			('Doctor of Medicine Unani(Mahir e Tibb)','Doctor of Medicine Unani(Mahir e Tibb)'),
			('Doctor of Medicine(M.D)','Doctor of Medicine(M.D)'),
			('Executive Fellow Program In Management(E.F.P.M)','Executive Fellow Program In Management(E.F.P.M)'),
			('Executive Management Programme(E.M.P)','Executive Management Programme(E.M.P)'),
			('Fellow Programme in Management(F.P.M)','Fellow Programme in Management(F.P.M)'),
			('MA / MSc Mathematics','MA / MSc Mathematics'),
			('MA Adult & Continuing Education','MA Adult & Continuing Education'),
			('MA Ancient History & Archeology','MA Ancient History & Archeology'),
			('MA Anthropology','MA Anthropology'),
			('MA Applied Economics','MA Applied Economics'),
			('MA Dance','MA Dance'),
			('MA Economics','MA Economics'),
			('MA English','MA English'),
			('MA Hindi','MA Hindi'),
			('MA History','MA History'),
			('MA Human Rights & Duties','MA Human Rights & Duties'),
			('MA Music','MA Music'),
			('MA Philosophy','MA Philosophy'),
			('MA Political Science','MA Political Science'),
			('MA Psychology','MA Psychology'),
			('MA Public Administration','MA Public Administration'),
			('MA Sanskrit','MA Sanskrit'),
			('MA Social Work','MA Social Work'),
			('MA Sociology','MA Sociology'),
			('Management Development Programme(M.D.P)','Management Development Programme(M.D.P)'),
			('Master of Architecture(M.Arch)','Master of Architecture(M.Arch)'),
			('Master of Arts in Management(M.A.M)','Master of Arts in Management(M.A.M)'),
			('Master of Arts in Personal Management(M.A.P.M)','Master of Arts in Personal Management(M.A.P.M)'),
			('Master of Arts in Theatre & Television(M.A.T.T)','Master of Arts in Theatre & Television(M.A.T.T)'),
			('Master of Arts(M.A)','Master of Arts(M.A)'),
			('Master of Audiology & Speech Language Pathology(M.A.S.L.P)','Master of Audiology & Speech Language Pathology(M.A.S.L.P)'),
			('Master of Business Administration(M.B.A)','Master of Business Administration(M.B.A)'),
			('Master of Business Economics(M.B.E)','Master of Business Economics(M.B.E)'),
			('Master of Business Laws(M.B.L)','Master of Business Laws(M.B.L)'),
			('Master of Business Management(M.B.M)','Master of Business Management(M.B.M)'),
			('Master of Business Studies(M.B.S)','Master of Business Studies(M.B.S)'),
			('Master of Chirurgical(M.Ch)','Master of Chirurgical(M.Ch)'),
			('Master of Commerce(M.Com)','Master of Commerce(M.Com)'),
			('Master of Communication & Journalism(M.C.J)','Master of Communication & Journalism(M.C.J)'),
			('Master of Comparative Laws(M.C.L)','Master of Comparative Laws(M.C.L)'),
			('Master of Computer Applications(M.C.A)','Master of Computer Applications(M.C.A)'),
			('Master of Computer Management(M.C.M)','Master of Computer Management(M.C.M)'),
			('Master of Corporate Secretaryship(M.C.S)','Master of Corporate Secretaryship(M.C.S)'),
			('Master of Dental Surgery(M.D.S)','Master of Dental Surgery(M.D.S)'),
			('Master of education in Artificial Intelligence(M.Ed AI)','Master of education in Artificial Intelligence(M.Ed AI)'),
			('Master of Education(M.Ed)','Master of Education(M.Ed)'),
			('Master of Engineering(M.E)','Master of Engineering(M.E)'),
			('Master of Film Management(M.F.M)','Master of Film Management(M.F.M)'),
			('Master of Finance & Control(M.F.C)','Master of Finance & Control(M.F.C)'),
			('Master of Financial Services(M.F.S)','Master of Financial Services(M.F.S)'),
			('Master of Fine Arts(M.F.A)','Master of Fine Arts(M.F.A)'),
			('Master of Fishery Sciences(M.F.Sc)','Master of Fishery Sciences(M.F.Sc)'),
			('Master of Foreign Trade(M.F.T)','Master of Foreign Trade(M.F.T)'),
			('Master Of Health Science(M.H.Sc)','Master Of Health Science(M.H.Sc)'),
			('Master of Hospital Administration(M.H.A)','Master of Hospital Administration(M.H.A)'),
			('Master of Hospitality & Hotel Management(M.H.H.M)','Master of Hospitality & Hotel Management(M.H.H.M)'),
			('Master of Hospitality Management(M.H.M)','Master of Hospitality Management(M.H.M)'),
			('Master of Human Resource Management(M.H.R.M)','Master of Human Resource Management(M.H.R.M)'),
			('Master of Industrial Relation and Personal Management(MIR and PM)','Master of Industrial Relation and Personal Management(MIR and PM)'),
			('Master of Information Management(M.I.M)','Master of Information Management(M.I.M)'),
			('Master of International Business(M.I.B)','Master of International Business(M.I.B)'),
			('Master of Journalism(M.J)','Master of Journalism(M.J)'),
			('Master of Labour Management(M.L.M)','Master of Labour Management(M.L.M)'),
			('Master of Law(LL.M)','Master of Law(LL.M)'),
			('Master of Laws(M.L)','Master of Laws(M.L)'),
			('Master of Library and Information Science(M.L.I.Sc)','Master of Library and Information Science(M.L.I.Sc)'),
			('Master of Library Science(M.L.Sc)','Master of Library Science(M.L.Sc)'),
			('Master of Management Program(M.M.P)','Master of Management Program(M.M.P)'),
			('Master of Management Studies(M.M.S)','Master of Management Studies(M.M.S)'),
			('Master of Marketing Management(M.M.M)','Master of Marketing Management(M.M.M)'),
			('Master of Occupational Theraphy(M.O.T)','Master of Occupational Theraphy(M.O.T)'),
			('Master of Performance Management(M.P.M)','Master of Performance Management(M.P.M)'),
			('Master of Performing Arts(M.P.A)','Master of Performing Arts(M.P.A)'),
			('Master of Personal Management and Industrial Relation(MPM and IR)','Master of Personal Management and Industrial Relation(MPM and IR)'),
			('Master of Personnel Management(MPM)','Master of Personnel Management(MPM)'),
			('Master of Pharmacy(M.Pharma)","Master of Philosophy(M.Phil)','Master of Pharmacy(M.Pharma)","Master of Philosophy(M.Phil)'),
			('Master Of Physical Education(M.P.Ed)","Master of Physiotheraphy(M.P.T)','Master Of Physical Education(M.P.Ed)","Master of Physiotheraphy(M.P.T)'),
			('Master of Psychiatric Epidemiology(M.P.E)','Master of Psychiatric Epidemiology(M.P.E)'),
			('Master of Public Health(M.P.H)','Master of Public Health(M.P.H)'),
			('Master of Science(BOTANY)','Master of Science(BOTANY)'),
			('Master of Science(M.S)','Master of Science(M.S)'),
			('Master of Social Dynamics(M.S.D)','Master of Social Dynamics(M.S.D)'),
			('Master of Social Work(M.S.W)','Master of Social Work(M.S.W)'),
			('Master of Technology(M.Tech)','Master of Technology(M.Tech)'),
			('Master of Tourism Administrations(M.T.A)','Master of Tourism Administrations(M.T.A)'),
			('Master of Tourism Management(M.T.M)','Master of Tourism Management(M.T.M)'),
			('Master of Veterinary Science(M.V.Sc)','Master of Veterinary Science(M.V.Sc)'),
			('Masters of Hospitality and Tourism Management(M.H.T.M)','Masters of Hospitality and Tourism Management(M.H.T.M)'),
			('Masters of Public Systems Management(M.P.S.M)','Masters of Public Systems Management(M.P.S.M)'),
			('Masters Programme in International Business(M.P.I.B)','Masters Programme in International Business(M.P.I.B)'),
			('Masters Programme In Sports Physiotheraphy(M.S.P.T)','Masters Programme In Sports Physiotheraphy(M.S.P.T)'),
			('MSc Agricultural Biotechnology','MSc Agricultural Biotechnology'),
			('MSc Analysis of Foods, Drugs and Water','MSc Analysis of Foods, Drugs and Water'),
			('MSc Analytical Chemistry','MSc Analytical Chemistry'),
			('MSc Anthropology','MSc Anthropology'),
			('MSc Applied Chemistry','MSc Applied Chemistry'),
			('MSc Applied Mathematics','MSc Applied Mathematics'),
			('MSc Bio-Inorganic Chemistry','MSc Bio-Inorganic Chemistry'),
			('MSc Biochemistry','MSc Biochemistry'),
			('MSc Biotechnology','MSc Biotechnology'),
			('MSc Botany','MSc Botany'),
			('MSc Coastal Aquaculture & Marine Biotechnology','MSc Coastal Aquaculture & Marine Biotechnology'),
			('MSc Computer Science','MSc Computer Science'),
			('MSc Computer Science and Statistics','MSc Computer Science and Statistics'),
			('MSc Electronics & Instrumentation','MSc Electronics & Instrumentation'),
			('MSc Environmental Chemistry','MSc Environmental Chemistry'),
			('MSc Environmental Sciences','MSc Environmental Sciences'),
			('MSc Fishery Science','MSc Fishery Science'),
			('MSc Food, Nutrition Drugs and Water','MSc Food, Nutrition Drugs and Water'),
			('MSc Foods, Nutrition & Dietetics','MSc Foods, Nutrition & Dietetics'),
			('MSc Geography - B.A(Stream)','MSc Geography - B.A(Stream)'),
			('MSc Geography - B.Sc.(Stream)','MSc Geography - B.Sc.(Stream)'),
			('MSc Geology','MSc Geology'),
			('MSc Geophysics','MSc Geophysics'),
			('MSc Horticulture & Landscape Management','MSc Horticulture & Landscape Management'),
			('MSc Human Genetics','MSc Human Genetics'),
			('MSc Hydrology','MSc Hydrology'),
			('MSc Inorganic Chemistry','MSc Inorganic Chemistry'),
			('MSc Marine Biology and Fisheries','MSc Marine Biology and Fisheries'),
			('MSc Marine Biotechnology','MSc Marine Biotechnology'),
			('MSc Marine Chemistry','MSc Marine Chemistry'),
			('MSc Marine Geology','MSc Marine Geology'),
			('MSc Marine Geophysics','MSc Marine Geophysics'),
			('MSc Meteorology','MSc Meteorology'),
			('MSc Microbiology','MSc Microbiology'),
			('MSc Nuclear Chemistry','MSc Nuclear Chemistry'),
			('MSc Nuclear Physics','MSc Nuclear Physics'),
			('MSc Organic Chemistry','MSc Organic Chemistry'),
			('MSc Physical Chemistry','MSc Physical Chemistry'),
			('MSc Physical Oceanography','MSc Physical Oceanography'),
			('MSc Physics','MSc Physics'),
			('MSc Space Physics','MSc Space Physics'),
			('MSc Statistics','MSc Statistics'),
			('MSc VLSI Design, DSP & ESD','MSc VLSI Design, DSP & ESD'),
			('MSc Zoology','MSc Zoology'),
			('Others','Others'),
		)
	),
	('DOCTORATE',
		(
			('PhD in Accounting & Finance','PhD in Accounting & Finance'),
			('PhD in Alternative Medicine & Counseling','PhD in Alternative Medicine & Counseling'),
			('PhD in Agriculture','PhD in Agriculture'),
			('PhD in Medicine in General','PhD in Medicine in General'),
			('PhD in Anthropology','PhD in Anthropology'),
			('PhD in Ophthalmology','PhD in Ophthalmology'),
			('PhD in Archaeology','PhD in Archaeology'),
			('PhD in Other Medicine','PhD in Other Medicine'),
			('PhD in Biochemistry','PhD in Biochemistry'),
			('PhD in Pharmacy & Medicine','PhD in Pharmacy & Medicine'),
			('PhD in Bioinformatics','PhD in Bioinformatics'),
			('PhD in Physiotherapy','PhD in Physiotherapy'),
			('Occupational Health & Ergonomics','Occupational Health & Ergonomics'),
			('PhD in Biology Biomedical Life Sciences','PhD in Biology Biomedical Life Sciences'),
			('PhD in Psychology & Mental Health','PhD in Psychology & Mental Health'),
			('PhD in Biotechnology','PhD in Biotechnology'),
			('PhD in Surgery','PhD in Surgery'),
			('PhD in Biotechnology','PhD in Biotechnology'),
			('PhD in Botany','PhD in Botany'),
			('PhD in Chemical Engineering','PhD in Chemical Engineering'),
			('PhD in Civil Engineering','PhD in Civil Engineering'),
			('PhD in Creative Writing','PhD in Creative Writing'),
			('PhD in Economics','PhD in Economics'),
			('PhD in Electrical Engineering','PhD in Electrical Engineering'),
			('PhD in Electronics & Communication Engineering','PhD in Electronics & Communication Engineering'),
			('PhD in English','PhD in English'),
			('PhD in Environmental Science','PhD in Environmental Science'),
			('PhD in Fine Arts','PhD in Fine Arts'),
			('PhD in Future & Development Studies','PhD in Future & Development Studies'),
			('PhD in General Engineering','PhD in General Engineering'),
			('PhD in Genetics Engineering','PhD in Genetics Engineering'),
			('PhD in Geography & Geology','PhD in Geography & Geology'),
			('PhD in History','PhD in History'),
			('PhD in Home Science','PhD in Home Science'),
			('Others','Others'),
		)
	),
)

MIN_QUALIFICATION_YEAR = 30