# from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.conf.urls import patterns, include, url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^advisor_list/', views.advisor_list, name='advisor_list'),
    url(r'^view_advisor_modal/', views.view_advisor_modal, name='view_advisor_modal'),
    url(r'^activate_user/', views.activate_user, name='activate_user'),
    url(r'^de_activate_user/', views.de_activate_user, name='de_activate_user'),
    url(r'^mk_advisor/', views.grand_advisor, name='grand_advisor'),
    url(r'^mk_registered/', views.make_as_registered_advisor, 
        name='make_as_registered_advisor'),
    url(r'^mk_certified/', views.make_as_certified_advisor, 
        name='make_as_certified_advisor'),
    url(r'^rm_advisor/', views.revoke_advisor, name='revoke_advisor'),
    url(r'^rm_registered/', views.make_as_unregistered_advisor, 
        name='make_as_unregistered_advisor'),
    url(r'^rm_certified/', views.make_as_uncertified_advisor, 
        name='make_as_uncertified_advisor'),
    url(r'^certified_advisor/', views.certified_advisor, name='certified_advisor'),
    url(r'^remove_upload_file/', views.remove_upload_file, name='remove_upload_file'),
    url(r'^edit_user_profile_modal/', views.edit_user_profile_modal, 
        name='edit_user_profile_modal'),
    url(r'^save_user_profile_model/', views.save_user_profile_model, 
        name='save_user_profile_model'),
    url(r'^user_checkpin/', views.user_checkpin, name='user_checkpin'),
    url(r'^mk_confirmed/', views.make_confirmed_advisor, name='make_confirmed_advisor'),
    url(r'^mk_not_confirmed/', views.make_not_confirmed_advisor, 
        name='make_not_confirmed_advisor'),
    url(r'^mk_aggrigate_advisor/', views.make_aggrigate_advisor, 
        name='make_aggrigate_advisor'),
    # CRISIL Applications URLS
    url(r'^crisil_advisor_list/', views.crisil_advisor_list, name='crisil_advisor_list'),
    url(r'^crisil_admin_panel/', views.crisil_admin_panel, name='crisil_admin_panel'),
    url(r'^crisil_payment_details/', views.crisil_payment_details, 
        name='crisil_payment_details'),
    url(r'^crisil_verified/', views.crisil_verified, name='crisil_verified'),
    url(r'^crisil_expired/', views.crisil_expired, name='crisil_expired'),
    url(r'^view_crisil_advisor_modal/', views.view_crisil_advisor_modal, 
        name='view_crisil_advisor_modal'),
    url(r'^edit_crisil_advisor_modal/', views.edit_crisil_advisor_modal, 
        name='edit_crisil_advisor_modal'),
    url(r'^crisil_certificate_modal/', views.crisil_certificate_modal, 
        name='crisil_certificate_modal'),
    url(r'^edit_crisil_certificate_modal/', views.edit_crisil_certificate_modal, 
        name='edit_crisil_certificate_modal'),
    url(r'^affiliated_companies/', views.affiliated_companies, 
        name='affiliated_companies'),
    url(r'^send_mail_to_company/', views.send_mail_to_company, 
        name='send_mail_to_company'),
    url(r'^add_client_list/', views.add_client_list, name='add_client_list'),
    url(r'^view_member_modal/', views.view_member_modal, name='view_member_modal'),
    url(r'^edit_member_profile_modal/', views.edit_member_profile_modal, 
        name='edit_member_profile_modal'),
    url(r'^view_company_details/', views.view_company_details, 
        name="view_company_details"),
    url(r'^view_company_details_resend/', views.view_company_details_resend, 
        name="view_company_details_resend"),
    url(r'^create_company/', views.create_company, name='create_company'),
    url(r'^company_spoc/', views.company_spoc, name='company_spoc'),
    url(r'^save_crisil_feedback/', views.save_crisil_feedback, 
        name='save_crisil_feedback'),
    url(r'^view_crisil_failed_feedback/', views.view_crisil_failed_feedback, 
        name='view_crisil_failed_feedback'),
    url(r'^resend_mail_to_company/', views.resend_mail_to_company, 
        name='resend_mail_to_company'),
    url(r'^get_company_activation/', views.get_company_activation, 
        name='get_company_activation'),
    url(r'^crisil_renewal/', views.crisil_renewal, name='crisil_renewal'),
    url(r'^advisor_video_request/', views.advisor_video_request, 
        name='advisor_video_request'),
    url(r'^approve_video_request/', views.approve_video_request, 
        name='approve_video_request'),
    url(r'^advisor_video_publish/', views.advisor_video_publish, 
        name='advisor_video_publish'),
    url(r'^video_publish_approved/', views.video_publish_approved,
        name='video_publish_approved'),
    url(r'^video_publish_reject/', views.video_publish_reject, 
        name='video_publish_reject'),
    url(r'^view_video_request_details/', views.view_video_request_details, 
        name='view_video_request_details'),
    url(r'^upload_company_excel_file/', views.upload_company_excel_file, 
        name='upload_company_excel_file'),
    url(r'^subscription-package/', views.subscription_package, 
        name='subscription_package'),
    url(r'^get-feature-list/', views.get_feature_list, name='get_feature_list'),
    # uncomment this url for dynamic adding fetaures to package
    # url(r'^create-package/', views.subscription_package, name='subscription_package'),
    url(r'^regulatory_registration_data_uploaded_url/', 
        views.list_regulatory_registration_docs_uploaded, 
        name='list_regulatory_registration_docs_uploaded'
    ),
    url(r'^verify_uploaded_regulatory_doc/', 
        views.verify_uploaded_regulatory_document, 
        name='verify_uploaded_regulatory_document'
    ),
    url(r'^verify_uploaded_regulatory_renewal_doc/', 
        views.verify_uploaded_regulatory_renewal_document, 
        name='verify_uploaded_regulatory_renewal_document'
    ),
    url(r'^reject_uploaded_regulatory_doc/', 
        views.reject_uploaded_regulatory_document, 
        name='reject_uploaded_regulatory_document'
    ),
    url(r'^educational_authentication/', 
        views.educational_authentication, name='educational_authentication'),
    url(r'^load_additional_qual_list/', 
        views.load_additional_qual_list, name='load_additional_qual_list'),
    url(r'^get_additional_qual_doc_url/', views.get_additional_qual_doc_url, name='get_additional_qual_doc_url'),
    url(r'^verify_heighest_qua_doc/', 
        views.verify_heighest_qua_doc, name='verify_heighest_qua_doc'),
    url(r'^verify_additional_qua_document/', 
        views.verify_additional_qua_document, name='verify_additional_qua_document'),
    url(r'^load_rera_regulatory_list/', 
        views.load_rera_regulatory_list, name='load_rera_regulatory_list'),
    url(r'^publish_newsletter/', views.publish_newsletter,
        name='publish_newsletter'),
    url(r'^publish_testimonial/', views.publish_testimonial,
        name='publish_testimonial'),
    url(
        r'^nfadmins_edit_or_view_image/',
        TemplateView.as_view(
            template_name="nfadmin/nfadmins_edit_or_view_picture.html"
        )
    ),
    url(r'^delete_testimonial/', views.delete_testimonial,
        name='delete_testimonial'),
    url(r'^nfadmins_edit_or_view_form/', views.nfadmins_edit_or_view_form,
        name='nfadmins_edit_or_view_form')
]

