# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_check', '0005_advisor_check_remove_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmfiData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('arn', models.CharField(db_index=True, max_length=50, unique=True, null=True, blank=True)),
                ('name', models.CharField(db_index=True, max_length=150, null=True, blank=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('pincode', models.CharField(max_length=15, null=True, blank=True)),
                ('email', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('city', models.CharField(max_length=25, null=True, blank=True)),
                ('mobile', models.CharField(db_index=True, max_length=25, null=True, blank=True)),
                ('mobile2', models.CharField(max_length=25, null=True, blank=True)),
                ('source', models.CharField(max_length=150, null=True)),
                ('valid_till', models.CharField(max_length=20, null=True, blank=True)),
                ('valid_from', models.CharField(max_length=20, null=True, blank=True)),
                ('kyd_complaint', models.CharField(max_length=25, null=True, blank=True)),
                ('euin', models.CharField(max_length=15, null=True, blank=True)),
                ('advisor_id', models.IntegerField(null=True, blank=True)),
                ('claimed_status', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CaData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('reg_id', models.CharField(db_index=True, max_length=50, unique=True, null=True, blank=True)),
                ('sub_category', models.CharField(max_length=20, null=True, blank=True)),
                ('name', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('city', models.CharField(max_length=50, null=True, blank=True)),
                ('pincode', models.CharField(max_length=15, null=True, blank=True)),
                ('email', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('secondary_email', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('landline', models.CharField(max_length=25, null=True, db_index=True)),
                ('mobile', models.CharField(max_length=25, null=True, db_index=True)),
                ('mobile2', models.CharField(max_length=25, null=True, db_index=True)),
                ('source', models.CharField(max_length=150, null=True)),
                ('company', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('advisor_id', models.IntegerField(null=True, blank=True)),
                ('claimed_status', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IrdaData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('license_no', models.CharField(max_length=150, unique=True, null=True, db_index=True)),
                ('agent_id', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=250, null=True, db_index=True)),
                ('email', models.CharField(max_length=250, null=True, blank=True)),
                ('mobile', models.CharField(max_length=25, null=True, db_index=True)),
                ('mobile2', models.CharField(max_length=25, null=True, db_index=True)),
                ('source', models.CharField(max_length=150, null=True)),
                ('organization', models.CharField(max_length=150, null=True)),
                ('irda_urn', models.TextField(null=True, blank=True)),
                ('sub_category', models.TextField(null=True, blank=True)),
                ('company', models.CharField(max_length=250, null=True)),
                ('dp_id', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('district', models.CharField(max_length=50, null=True)),
                ('pin_code', models.CharField(max_length=10, null=True)),
                ('valid_from', models.CharField(max_length=50, null=True)),
                ('valid_till', models.CharField(max_length=50, null=True)),
                ('absorbed_agent', models.CharField(max_length=150, null=True)),
                ('advisor_id', models.IntegerField(null=True, blank=True)),
                ('claimed_status', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SebiData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('reg_no', models.CharField(db_index=True, max_length=50, unique=True, null=True, blank=True)),
                ('name', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('contact_person', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('address', models.TextField(null=True, blank=True)),
                ('email', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('mobile', models.CharField(max_length=25, null=True, db_index=True)),
                ('fax', models.CharField(max_length=25, null=True, blank=True)),
                ('city', models.CharField(max_length=50, null=True, blank=True)),
                ('state', models.CharField(max_length=50, null=True, blank=True)),
                ('pincode', models.CharField(max_length=15, null=True, blank=True)),
                ('type_of_intermediary', models.CharField(max_length=50, null=True, blank=True)),
                ('secondary_address', models.TextField(null=True, blank=True)),
                ('secondary_email', models.CharField(db_index=True, max_length=250, null=True, blank=True)),
                ('secondary_mobile', models.CharField(max_length=25, null=True, db_index=True)),
                ('secondary_fax', models.CharField(max_length=25, null=True, blank=True)),
                ('secondary_city', models.CharField(max_length=50, null=True, blank=True)),
                ('secondary_state', models.CharField(max_length=50, null=True, blank=True)),
                ('secondary_pincode', models.CharField(max_length=15, null=True, blank=True)),
                ('valid_from', models.CharField(max_length=20, null=True, blank=True)),
                ('valid_till', models.CharField(max_length=20, null=True, blank=True)),
                ('country', models.CharField(max_length=20, null=True, blank=True)),
                ('fii_name', models.CharField(max_length=50, null=True, blank=True)),
                ('exchange_name', models.CharField(max_length=150, null=True, blank=True)),
                ('trade_name', models.CharField(max_length=50, null=True, blank=True)),
                ('affiliated_broker', models.CharField(max_length=50, null=True, blank=True)),
                ('affiliated_broker_reg_no', models.CharField(max_length=50, null=True, blank=True)),
                ('source', models.CharField(max_length=150, null=True)),
                ('advisor_id', models.IntegerField(null=True, blank=True)),
                ('claimed_status', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='advisordata',
            old_name='advisor_type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='advisordata',
            name='constitution',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='advisordata',
            name='source_link',
            field=models.TextField(null=True, blank=True),
        ),
    ]
