# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor_check', '0006_create_sebi_amfi_irda_cadata_update_on_advisordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BseData',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('authorised_persons', models.CharField(max_length=50, null=True, blank=True)),
                ('bse_clearing_number', models.CharField(db_index=True, max_length=50, unique=True, null=True, blank=True)),
                ('belongs_to_business_group', models.CharField(max_length=50, null=True, blank=True)),
                ('board_of_directors_designation', models.CharField(max_length=500, null=True, blank=True)),
                ('board_of_directors_name', models.CharField(max_length=500, null=True, blank=True)),
                ('branch_offices', models.TextField(null=True, blank=True)),
                ('broker_type', models.CharField(max_length=50, null=True, blank=True)),
                ('change_in_status_constitution_of_ap', models.CharField(max_length=250, null=True, blank=True)),
                ('chief_executive', models.CharField(max_length=500, null=True, blank=True)),
                ('compliance_officer_1', models.CharField(max_length=250, null=True, blank=True)),
                ('compliance_officer_2', models.CharField(max_length=250, null=True, blank=True)),
                ('composite_corporate_membership', models.CharField(max_length=50, null=True, blank=True)),
                ('constitution', models.CharField(max_length=500, null=True, blank=True)),
                ('contact_no', models.CharField(max_length=250, null=True, blank=True)),
                ('corporate_email', models.CharField(max_length=250, null=True, blank=True)),
                ('correspondence_office', models.TextField(null=True, blank=True)),
                ('sebi_registration_date', models.CharField(max_length=50, null=True, blank=True)),
                ('de_recognition_or_acceptance_date', models.CharField(max_length=50, null=True, blank=True)),
                ('diciplinery_action_against_ap', models.CharField(max_length=50, null=True, blank=True)),
                ('direct_phone', models.CharField(max_length=50, null=True, blank=True)),
                ('fax', models.CharField(max_length=50, null=True, blank=True)),
                ('listed_at', models.CharField(max_length=50, null=True, blank=True)),
                ('member_name', models.CharField(max_length=250, null=True, blank=True)),
                ('member_mapin', models.CharField(max_length=50, null=True, blank=True)),
                ('other_indian_stock_exchanges_in_same_entity_clearing_no', models.CharField(max_length=250, null=True, blank=True)),
                ('other_indian_stock_exchanges_in_same_entity_name_of_exchange', models.CharField(max_length=500, null=True, blank=True)),
                ('other_indian_stock_exchanges_in_same_entity_sebi_registration_no', models.CharField(max_length=250, null=True, blank=True)),
                ('no_of_terminals', models.CharField(max_length=50, null=True, blank=True)),
                ('old_name_1_of_member', models.CharField(max_length=50, null=True, blank=True)),
                ('old_name_2_of_member', models.CharField(max_length=50, null=True, blank=True)),
                ('old_name_3_of_member', models.CharField(max_length=50, null=True, blank=True)),
                ('other_capital_market_activities_name', models.CharField(max_length=250, null=True, blank=True)),
                ('other_capital_market_activities_sebi_registration_no', models.CharField(max_length=250, null=True, blank=True)),
                ('other_capital_market_activities_sebi_registration_start_date', models.CharField(max_length=250, null=True, blank=True)),
                ('other_group_companies_in_the_capital_market_area_activity', models.TextField(null=True, blank=True)),
                ('other_group_companies_in_the_capital_market_area_company_name', models.TextField(null=True, blank=True)),
                ('phones', models.CharField(max_length=250, null=True, blank=True)),
                ('pincode', models.CharField(max_length=50, null=True, blank=True)),
                ('products_or_services_handled', models.CharField(max_length=50, null=True, blank=True)),
                ('profile_of_member_as_submitted_by_member', models.TextField(null=True, blank=True)),
                ('reference_to_bse_clearing_number', models.CharField(max_length=50, null=True, blank=True)),
                ('registered_office', models.TextField(null=True, blank=True)),
                ('remisiers', models.CharField(max_length=50, null=True, blank=True)),
                ('sebi_registration_no', models.CharField(max_length=50, null=True, blank=True)),
                ('sebi_registration_no_for_currency_derivatives', models.CharField(max_length=250, null=True, blank=True)),
                ('sebi_registration_no_for_currency_derivatives_date', models.CharField(max_length=250, null=True, blank=True)),
                ('segment_and_status_all_segments', models.CharField(max_length=250, null=True, blank=True)),
                ('state', models.CharField(max_length=250, null=True, blank=True)),
                ('status', models.CharField(max_length=50, null=True, blank=True)),
                ('sub_brokers', models.CharField(max_length=50, null=True, blank=True)),
                ('subsidiary_status', models.CharField(max_length=50, null=True, blank=True)),
                ('terminal_details', models.CharField(max_length=250, null=True, blank=True)),
                ('trade_name', models.TextField(null=True, blank=True)),
                ('type', models.CharField(max_length=250, null=True, blank=True)),
                ('types_of_clients_served', models.CharField(max_length=250, null=True, blank=True)),
                ('website', models.CharField(max_length=250, null=True, blank=True)),
                ('year_broking_business_started', models.CharField(max_length=50, null=True, blank=True)),
                ('year_of_bse_membership', models.CharField(max_length=50, null=True, blank=True)),
                ('year_of_incorporation', models.CharField(max_length=250, null=True, blank=True)),
                ('city', models.CharField(max_length=250, null=True, blank=True)),
                ('segment_status', models.TextField(null=True, blank=True)),
                ('source_link', models.CharField(max_length=250, null=True, blank=True)),
                ('advisor_id', models.IntegerField(null=True, blank=True)),
                ('claimed_status', models.CharField(max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
