# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0116_advisor_id_added_to_getadvice_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_address_line_1',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_address_line_2',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_city',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_country',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_location',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_phone_no',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_pincode',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='alternate_state',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='faxno',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_alternate_address',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_filled_address',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_filled_identity',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_investment_admin',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_project_admin',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_project_coordinator',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='is_trustee',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='know_duration',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='know_how',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='no_of_child',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='politically_status',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='resedential_status',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='historicaluserprofile',
            name='voter_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_address_line_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_phone_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_pincode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_state',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='faxno',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_alternate_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_developer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_filled_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_filled_identity',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_investment_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_project_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_project_coordinator',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_trustee',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='know_duration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='know_how',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='no_of_child',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='politically_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resedential_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='voter_id',
        ),
    ]
